FROM linuxserver/code-server:4.9.0
ARG ARCH=/script.sh

# set version label
LABEL maintainer="marek@techfellow.it"

# environment settings
ENV HOME="/home/vsadmin"

# add local files
COPY ./root/ /

RUN sh $ARCH
# ports and volumes

EXPOSE 80
