---
version: "3.6"
services:
  col:
    # build: .
    image: techfellow/col
    container_name: col
    hostname: col
    ports:
      - "8080:80"
    mem_limit: 512m
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - HOSTNAME=col
    volumes:
      - colvol:/config
#      - ./lab:/config/lab

    restart: unless-stopped

#     mac_address: 02:42:c0:a8:32:f9

#     networks:
#       default:
#         ipv4_address: 192.168.30.240

# networks:
#   default:
#    external:
#     name: macvlan

volumes:
  colvol: