---
version: "3.6"
services:
  col:
    build: .
    container_name: col
    ports:
      - "8080:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - HOSTNAME=col
    volumes:
        - ./config:/config
#      - ./lab:/config/lab
  
    restart: unless-stopped

