#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

#useradd -m -d /home/ -s /bin/bash madmin
groupmod -o -g "$PGID" madmin
usermod -o -u "$PUID" madmin
# usermod -aG users,sudo madmin

echo '
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u madmin)
User gid:    $(id -g madmin)
-------------------------------------
"
chown -R madmin:madmin /app
chown -R madmin:madmin /config
chown -R madmin:madmin /home/madmin
