---
version: "3.3"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - './config:/config'
    ports:
      - 80:80
      - 443:443
    
    mem_limit: 256m

    restart: unless-stopped

#     mac_address: 02:42:c0:a8:dd:ee

#     networks:
#       default:
#           ipv4_address: 192.168.30.242

# networks:
#   default:
#     external:
#       name: macvlan
#     ipam:
#       config:
#         - subnet: 192.168.30.240/29
