services:
  web:
    image: techfellow/ipcheck:latest
    networks:
      - lbnet
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000
    deploy:
      replicas: 12
      endpoint_mode: dnsrr
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 64M

  haproxy:
    image: haproxy:3.0
    depends_on:
      - web
    ports:
      - target: 80
        published: 80
        mode: host # Direct bound to host port 80
      - target: 8404
        published: 8404
        mode: host # Direct bound to host port 8404
    configs:
      - source: haproxy_cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
    networks:
      - lbnet
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000
    deploy:
      mode: global # Exactly 1 replica on each node and cannot scale more
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 64M
      # mode: global # For one replica per node

configs:
  haproxy_cfg:
    file: ./haproxy.cfg

networks:
  lbnet:
    driver: overlay
    attachable: true
