# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

ARG imageRepo=ubuntu
ARG fromTag=noble

FROM ${imageRepo}:${fromTag}

ENV PS_INSTALL_FOLDER=/opt/microsoft/powershell/7 \
    TZ=Europe/Warsaw \
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    UBUNTU=24.04 \
    PSModuleAnalysisCachePath=/var/cache/microsoft/powershell/PSModuleAnalysisCache/ModuleAnalysisCache \
    POWERSHELL_DISTRIBUTION_CHANNEL=PSDocker-Ubuntu-24.04 \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y \
    ca-certificates \
    curl \
    git \
    gnupg \
    iputils-ping \
    less \
    libicu74 \
    libunwind8 \
    locales \
    nano \
    net-tools \
    wget

RUN wget -q https://packages.microsoft.com/config/ubuntu/${UBUNTU}/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb && apt update && apt install -y powershell && rm -rf /var/lib/apt/lists/* && locale-gen en_US.UTF-8

RUN pwsh -Command 'Set-PSRepository -Name PSGallery -InstallationPolicy Trusted'
# RUN pwsh -command 'update-module'
# RUN pwsh -command 'Install-module Az -Force'

# Use PowerShell as default shell
CMD [ "pwsh" ]

