services:
  web:
    image: httpdappa
    deploy:
      replicas: 12
    mem_limit: 8m
    environment:
      - TZ=Europe/Warsaw
    networks:
      - ipnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ipcheck.entrypoints=web"
      - "traefik.http.routers.ipcheck.rule=Host(`weblb.local`) || Host(`localhost`)"
      - "traefik.http.services.ipcheck.loadbalancer.server.port=80"
    restart: always

  traefik:
    image: traefik:v3.7
    container_name: traefik
    mem_limit: 128m
    restart: always
    depends_on:
      - web
    networks:
      - ipnet
    ports:
      - "80:80"
      - "8080:8080" # Enables access to Traefik Dashboard (http://localhost:8080)
    volumes:
      - ./configuration/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.docker.network=ipnet"

networks:
  ipnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.25.0/24
          gateway: 172.25.25.1
