version: "3.3"
services:
  ipcheck:
    image: techfellow/ipcheck:ubuntu
    networks:
      - ipcheck
    ports:
      - "5080:80"
      - "5443:443"
    environment:
      TZ: 'Europe/Warsaw'
    deploy:
      replicas: 6
      mode: replicated
      update_config:
        delay: 1s
#        order: start-first
        parallelism: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
      resources:
        limits:
          cpus: '2'
          memory: 64M

networks:
  ipcheck:

