FROM ubuntu:20.04
RUN apt update -qq && apt install -y --no-install-recommends python3 python3-pip
RUN pip install gunicorn flask
COPY ipcheck.py /
CMD ["gunicorn", "--bind", "0.0.0.0:80", "ipcheck"]
