FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/Warsaw
RUN apt-get update -qq && apt-get install -y --no-install-recommends python3 python3-pip
RUN pip install gunicorn flask

COPY ipcheck.py /
EXPOSE 80

CMD ["gunicorn", "--bind", "0.0.0.0:80", "ipcheck"]
