services:
  ipcheck:
    image: techfellow/ipcheck:latest
    networks:
      - ipcheck
    ports:
      - "5080:80"
    environment:
      TZ: "Europe/Warsaw"
    deploy:
      replicas: 6
      mode: replicated
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 2
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
      resources:
        reservations:
          cpus: "0.2"
          memory: 32M
        limits:
          cpus: "1"
          memory: 64M

networks:
  ipcheck:
    driver: overlay
