---
version: "3.3"
services:
  web:
    image: techfellow/webappa:latest
    deploy:
      replicas: 4
    mem_limit: 8m
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000
    restart: always

    networks:
       - lbnet
        # ipv4_address: 172.30.30.3/27
    # volumes:
    #   - ./data:/usr/share/nginx/html

  haproxy:
    image: haproxy:2.4
    # hostname: haproxy
    depends_on:
      - web
    deploy:
      replicas: 1
    networks:
      lbnet:
        ipv4_address: 172.30.30.6
    ports:
      - 80:80
    mem_limit: 32m
#    mem_reservation: 100m
    restart: always
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000
    volumes:
      - ./:/usr/local/etc/haproxy/

volumes:
  data:
    external: false

networks:
  lbnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.30.30.0/29
         gateway: 172.30.30.1