services:
  newnginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ./data:/usr/share/nginx/html

    # volumes:
    #   - type: volume
    #     source: data3
    #     target: /usr/share/nginx/html


# volumes:
#   data3:
#     external: false

