---
version: "3"
services:
  newnginx:
    image: nginx:latest
    hostname: nginx
    deploy:
      replicas: 1
    #    command:  sleep 5
    restart: always
    environment:
      - TZ=Europe/Warsaw
    ports:
      - 80:80

    volumes:
      - ./data:/usr/share/nginx/html

    # volumes:
    #   - type: volume
    #     source: data3
    #     target: /usr/share/nginx/html


volumes:
  data3:
    external: false

