---
version: "3.6"
services:
  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - PASSWORD=simpass111
      - CUSTOM_RESULTS=true #optional
      - DB_TYPE=sqlite #optional
      - DB_NAME=librespeeddb1 #optional
#      - DB_HOSTNAME=DB_HOSTNAME #optional
#      - DB_USERNAME=DB_USERNAME #optional
#      - DB_PASSWORD=DB_PASSWORD #optional
    volumes:
      - './config:/config'
    ports:
      - 8081:80

    restart: unless-stopped

#    networks:
#      - default

#networks:
#  default:
#    external:
#      name: macvlan
