### Docker compose 2.0
version: '3.6'

services:
  db:
    image: linuxserver/mariadb:latest
    container_name: wpdb
    mem_limit: 128m
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: simpleandfastpasswordfordb22
      MYSQL_DATABASE: wpdb2022
      MYSQL_USER: wpdbuser22
      MYSQL_PASSWORD: wpdbpass22
      TZ: Europe/Warsaw
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8091:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      TZ: Europe/Warsaw
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp
    mem_limit: 256m
    ports:
       - '8090:80'
    restart: always
    volumes:
      - wordpress:/var/www/html
#    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wpdb2022
      WORDPRESS_DB_USER: wpdbuser22
      WORDPRESS_DB_PASSWORD: wpdbpass22
      TZ: Europe/Warsaw
    networks:
      - wpsite

networks:
   wpsite:
volumes:
   db_data:
   wordpress:
