<<<<<<< HEAD
version: '3.3'

services:
   wpdb2022:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpressmadmin2022
       MYSQL_PASSWORD: wordpresspass2022
       TZ: Europe/Warsaw

   wordpress2022:
     depends_on:
       - wpdb2022
     image: wordpress:latest
     ports:
       - "9080:80"
       - "9443:443"
     restart: always
     environment:
       WORDPRESS_DB_HOST: wpdb2022:3306
       WORDPRESS_DB_USER: wordpressmadmin2022
       WORDPRESS_DB_PASSWORD: wordpresspass2022
       TZ: Europe/Warsaw
=======
services:
  db:
    image: linuxserver/mariadb:latest
    container_name: wpdb
    mem_limit: 128m
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: simpleandfastpasswordfordb22
      MYSQL_DATABASE: wpdb2022
      MYSQL_USER: wpdbuser22
      MYSQL_PASSWORD: wpdbpass22
      TZ: Europe/Warsaw
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8091:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      TZ: Europe/Warsaw
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp
    mem_limit: 256m
    ports:
       - '8090:80'
    restart: always
    volumes:
      - wordpress:/var/www/html
#    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wpdb2022
      WORDPRESS_DB_USER: wpdbuser22
      WORDPRESS_DB_PASSWORD: wpdbpass22
      TZ: Europe/Warsaw
    networks:
      - wpsite

networks:
   wpsite:
volumes:
   db_data:
   wordpress:

>>>>>>> 7d8d344fab2dbc02b5aafed21d807ef751ba0d0b
