---
version: "3"

services:
  website:
#    build: .
    image: techfellow/httpdapp
    container_name: website
    mem_limit: 32m
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      TZ: 'Europe/Warsaw'

    restart: unless-stopped
#    deploy:
#      replicas: 5