services:
  website:
    image: techfellow/httpdappa:latest
    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: ingress
    environment:
      - TZ=Europe/Warsaw
    deploy:
      # labels:
      #   servicename: website
      replicas: 6
      mode: replicated
      # endpoint_mode: dnsrr
      # placement:
      #        constraints: [node.role == manager]
      # preferences:
      #   - spread: node.labels.dsw1
      update_config:
        parallelism: 2
        delay: 2s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 2
        delay: 2s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: "1.0"
          memory: 32M
        reservations:
          cpus: "0.1"
          memory: 16M
    networks:
      - website

networks:
  website:
    driver: overlay
    attachable: true
