---
version: "3"

services:
  httpdapp:
#    build: .
    image: techfellow/httpdapp:latest
    container_name: httpdapp
    mem_limit: 32m
    ports:
      - "8082:80"
    environment:
      TZ: 'Europe/Warsaw'
      
    restart: unless-stopped

  httpdappa:
#    build: .
    image: techfellow/httpdapp:alpine
    container_name: httpdappa
    mem_limit: 32m
    ports:
      - "8083:80"
    environment:
      TZ: 'Europe/Warsaw'

    restart: unless-stopped
