#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

#useradd -m -d /home/ -s /bin/bash vsadmin
groupmod -o -g "$PGID" vsadmin
usermod -o -u "$PUID" vsadmin
# usermod -aG users,sudo vsadmin

echo '
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u vsadmin)
User gid:    $(id -g vsadmin)
-------------------------------------
"
#chown vsadmin:vsadmin /config
#chown vsadmin:vsadmin /home/vsadmin
