services:
  web:
    # build: .
    image: ipcheck2
    deploy:
      replicas: 4
    mem_limit: 128m
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    networks:
      - lbnet
        # ipv4_address: 172.30.30.3/27

  haproxy:
    image: haproxy:3.0
    depends_on:
      - web
    ports:
      - "80:80"
      - "8404:8404"
    mem_limit: 64m
    restart: unless-stopped
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - lbnet

networks:
  lbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.30.0/24
          gateway: 172.30.30.1