#!/usr/bin/with-contenv bash

mkdir -p /config/{extensions,data,workspace}
mkdir -p /config/data/logs

chown -R madmin:madmin /config/

# if [ -n "${SUDO_PASSWORD}" ] || [ -n "${SUDO_PASSWORD_HASH}" ]; then
#   echo "setting up sudo access"
#   if ! grep -q 'madmin' /etc/sudoers; then
#     echo "adding madmin to sudoers"
#     echo "madmin ALL=(ALL:ALL) ALL" >> /etc/sudoers
#   fi
#   if [ -n "${SUDO_PASSWORD_HASH}" ]; then
#     echo "setting sudo password using sudo password hash"
#     sed -i "s|^madmin:\!:|madmin:${SUDO_PASSWORD_HASH}:|" /etc/shadow
#   else
#     echo "setting sudo password using SUDO_PASSWORD env var"
#     echo -e "${SUDO_PASSWORD}\n${SUDO_PASSWORD}" | passwd madmin
#   fi
# fi

# permissions
# chown -R madmin:madmin /config
# chown -R madmin:madmin /home/madmin