---
version: "3"
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./portainer/portainer_data:/data
    ports:
      - 9000:9000
      - 8000:8000

    restart: always
