---
version: '3.7'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_SECRET: ${AGENT_SECRET}
      TZ: Europe/Warsaw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    depends_on:
      - portal
    deploy:
      mode: global
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
        parallelism: 1
      resources:
        reservations:
          memory: 20M
        limits:
          memory: 64M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
    networks:
      -  portainer
  portal:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify --admin-password='${PASSWORD}'
    environment:
      TZ: Europe/Warsaw
      AGENT_SECRET: ${AGENT_SECRET}
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
        parallelism: 1
      resources:
        reservations:
          memory: 20M
        limits:
          memory: 128M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      -  portainer

networks:
  portainer:
    name: portainer
    driver: overlay
    attachable: true