#!/bin/sh

# set -eu

PS_VERSION=7.6.6
DOCKER_VERSION=24.0.6
TF_VERSION=1.16.5
USER=madmin
TMP=$(mktemp -d)
HW=$(uname -m)

echo 'Install script for code on lan environment'

export DEBIAN_FRONTEND=noninteractive
export HOME="/home/$USER"

echo "**** Packages ****"
apt-get update
apt-get install -y mc tmux htop mtr-tiny nano wget iputil* net-tools nmap unzip dialog
apt-get install -y --no-install-recommends ca-certificates curl apt-transport-https lsb-release gnupg libssl-dev libffi-dev python3-dev build-essential git libunwind8 less tzdata ansible-core

case "$(uname -m)" in
  x86_64)  PS_ARCH=x64;   DOCKER_ARCH=x86_64;  TF_ARCH=amd64 ;;
  aarch64) PS_ARCH=arm64; DOCKER_ARCH=aarch64; TF_ARCH=arm64 ;;
  *) echo "Unsupported platform: $(uname -m)"; exit 1 ;;
esac
echo "Architecture: $(uname -m)"

echo "**** AZ CLI Installation ****"
curl -fsSL https://aka.ms/InstallAzureCLIDeb | bash

echo "**** Installing Powershell ****"
PS_PACKAGE=powershell-$PS_VERSION-linux-$PS_ARCH.tar.gz
curl -fsSL "https://github.com/PowerShell/PowerShell/releases/download/v$PS_VERSION/$PS_PACKAGE" -o "$TMP/$PS_PACKAGE"
mkdir -p /usr/local/share/pwsh/
tar -xzf "$TMP/$PS_PACKAGE" -C /usr/local/share/pwsh/
chown -R root:root /usr/local/share/pwsh && chmod 755 /usr/local/share/pwsh/pwsh
ln -s /usr/local/share/pwsh/pwsh /usr/bin/pwsh

echo "**** Powershell Gallery ****"
pwsh -command set-psrepository -name PSGallery -installationpolicy trusted

# echo "**** Installing Powershell AZ Module ****" 
#pwsh -command install-module az -force

echo "**** Installing Docker client ****"
DOCKER_PACKAGE=docker-$DOCKER_VERSION.tgz
curl -fsSL "https://download.docker.com/linux/static/stable/$DOCKER_ARCH/$DOCKER_PACKAGE" -o "$TMP/$DOCKER_PACKAGE"
tar -xzf "$TMP/$DOCKER_PACKAGE" -C /usr/local/share/
ln -s /usr/local/share/docker/docker /usr/bin/docker

echo "**** Installing Terraform ****"
TF_PACKAGE=terraform_${TF_VERSION}_linux_${TF_ARCH}.zip
curl -fsSL "https://releases.hashicorp.com/terraform/$TF_VERSION/$TF_PACKAGE" -o "$TMP/$TF_PACKAGE"
unzip "$TMP/$TF_PACKAGE" terraform -d /usr/bin/

echo "**** Cleanup ****"
apt-get autoremove -y
apt-get purge -y
apt-get clean
rm -rf /var/lib/apt/lists/* "$TMP" /defaults
userdel abc
rm -rf /defaults

echo "**** Creating User ****"
useradd -m -d "/home/$USER" -G users,sudo -s /bin/bash "$USER"
echo "$USER ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/$USER"
chmod 440 "/etc/sudoers.d/$USER"
chown -R "$USER:$USER" /config

mkdir -p /config/data/User/
touch /config/data/User/settings.json
cat << EOFsettings > /config/data/User/settings.json 
{
    "workbench.colorTheme": "Visual Studio Dark",
    "terminal.integrated.gpuAcceleration": "off"
}
EOFsettings

echo "**** Files ****"

cat >> "/home/$USER/.bashrc" <<'EOF'
HISTSIZE=2000
HISTFILESIZE=2000
PATH=$PATH:/usr/local/share/az
PATH="$PATH:/usr/local/bin/"

export EDITOR='nano'

alias ttn='tmux attach -t new'
EOF

cat > "/home/$USER/.selected_editor" <<'EOF'
# Generated by /usr/bin/select-editor
SELECTED_EDITOR="/bin/nano"
EOF

# TODO Step 4: remove this block and pass PASSWORD via .env instead
mkdir -p "/home/$USER/.config/code-server/"
cat > "/home/$USER/.config/code-server/config.yaml" <<'EOF'
bind-addr: 0.0.0.0:80
auth: password
password: orange!
cert: false
EOF

cat << 'EOFtmux' > "/home/$USER/.tmux.conf"
unbind %
bind | split-window -h
bind - split-window -v

set -g prefix C-l
unbind C-b
bind C-l send-prefix

# new-session -n $HOST
# set -g mouse on
# set -s escape-time 0

set -g status-interval 60
set -g default-terminal "screen-256color"

setw -g clock-mode-colour white

# Set status bar
set -g status-bg colour8
set -g status-fg white
set -g status-justify left
set -g status-right-length 80
set -g status-left-length 60
set -g status-right "#[fg=yellow]%H:%M | %d/%m"
set -g status-left  "#[fg=green]#H "
set -g terminal-overrides xterm*:smcup@:rmcup@

# setw -g window-status-bell-style 'fg=colour255 bg=colour1 bold'
EOFtmux

chown -R "$USER:$USER" "/home/$USER"

echo DONE
rm -f /script.sh /scriptarm.sh /scriptpc.sh
