---
version: '3.3'

services:
  kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    mem_limit: 128m

    volumes:
      - kuma_data:/app/data
    ports:
      - 80:3001

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw

    restart: unless-stopped

#    networks:
#      default:
#        ipv4_address: 192.168.30.243

#networks:
#  default:
#    external:
#    name: macvlan

volumes:
  kuma_data:

