#App image
FROM nginx:stable-alpine
LABEL maintainer="Marek from mysmall.cloud"

#COPY website/index.html /usr/share/nginx/html
COPY my-entrypoint.sh /
HEALTHCHECK --interval=1m --timeout=5s CMD curl -f http://localhost/ || exit 1

WORKDIR  /usr/share/nginx/html

EXPOSE 80
# RUN chown -R nginx:nginx /usr/share/nginx/html/

ENTRYPOINT ["/my-entrypoint.sh"]

#STOPSIGNAL SIGQUIT
#USER nginx

CMD ["nginx", "-g", "daemon off;"]
