#App image
FROM nginx:latest
LABEL maintainer="marek@techfellow.it"

#	RUN apt update && apt upgrade -y

# COPY website/index.html /usr/share/nginx/html
COPY my-entrypoint.sh /
HEALTHCHECK --interval=3m --timeout=5s CMD curl -f http://localhost/ || exit 1

WORKDIR  /usr/share/nginx/html

EXPOSE 80
#	EXPOSE 443
ENTRYPOINT ["/my-entrypoint.sh"]
#	USER 1000 
#    CMD ["/usr/local/nginx/sbin/nginx", "-g", "daemon off;"]

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
