---
version: "3.7"
services:
  webappa:
    image: techfellow/webappa:latest
    networks:
      - website
    ports:
      - "8080:80"
    environment:
      TZ: 'Europe/Warsaw'
      NGINX_HOST: web.local
      NGINX_PORT: 80
    deploy:
      replicas: 3
      mode: replicated
      update_config:
        delay: 1s
        order: start-first
        parallelism: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
      resources:
        limits:
          cpus: '1'
          memory: 32M
  
  httpdappa:
    image: techfellow/httpdappa
    networks:
      - website
    ports:
      - "8090:80"
    environment:
      TZ: 'Europe/Warsaw'
    deploy:
      replicas: 3
      mode: replicated
      update_config:
        delay: 1s
        order: start-first
        parallelism: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
      resources:
        limits:
          cpus: '1'
          memory: 32M

networks:
  website:
    